class Member:
    def __init__(self,LASTNAMEMEMBER,FIRSTNAMEMEMBER,LOGINMEMBER,PASSWORDMEMBER,CITYMEMBER,TELMEMBER):
        self.LASTNAMEMEMBER=LASTNAMEMEMBER
        self.FIRSTNAMEMEMBER=FIRSTNAMEMEMBER
        self.LOGINMEMBER=LOGINMEMBER
        self.PASSWORDMEMBER=PASSWORDMEMBER
        self.CITYMEMBER=CITYMEMBER
        self.TELMEMBER=TELMEMBER
        