class Book:
    def __init__(self,LOANDURATION,STATUBOOK,NAMEGENRE,NAMEBOOK,NUMSUP,NUMAUT,BOOKWRITINGDATE,DESCRIPTION):
        self.LOANDURATION=LOANDURATION
        self.STATUBOOK=STATUBOOK
        self.NAMEGENRE=NAMEGENRE
        self.NAMEBOOK=NAMEBOOK
        self.NUMSUP=NUMSUP
        self.NUMAUT=NUMAUT
        self.BOOKWRITINGDATE=BOOKWRITINGDATE
        self.DESCRIPTION=DESCRIPTION
    