class Author:
    def __init__(self,LASTNAMEAUT,FIRSTNAMEAUT,TELAUT,EMAILAUT):
        self.LASTNAMEAUT = LASTNAMEAUT
        self.FIRSTNAMEAUT = FIRSTNAMEAUT
        self.TELAUT = TELAUT
        self.EMAILAUT = EMAILAUT